### ISSUE TITLE
ctags multiline issue

### ISSUE THREAD

**Issue by AndiB** [cmatthew/Lind-misc#1]
Lind-misc / so_glue / ctags_stuff 

ctags cuts off protoypes spanning multiple lines as well as multiplie prototypes on one line.
example:
void bla(); void bla2(); 
^^^ this usually only takes the first one into ctags and loses the second one

void bla(int arg1,
    int arg2);
^^^ this cuts of the prototype after line 1 and loses the next lines 

SOLUTION: preprocess needs to be refined. put everything on one line and a new line after semi-colons.
This should also be seen as an opportunity to clean up the pre-processing

FIX LOCATION:
run me script or early in the ctags_parser.py

**Comment by cmatthew** [comment]
I don't think this is an issue anymore?
