### ISSUE TITLE
Lind FS file_copy.py broken

### ISSUE THREAD

**Issue by stredger** [cmatthew/Lind-misc#14]
I looks like the file_copy.py tool is broken

Here is the error:
<code>
$ file_copy.py test/test.txt test.txt
Traceback (most recent call last):
  File "/usr/local/bin/file_copy.py", line 20, in <module>
    import wrapped_lind_fs_calls as lind_fs_calls
ImportError: No module named wrapped_lind_fs_calls
</code>

**Comment by toadums** [comment]
ya...I think that is just cause I have the path to wrapped lind fs calls hard coded....I am not sure if there is another way to include it without just putting it in the directory.

**Comment by cmatthew** [comment]
Fixed.
