### ISSUE TITLE
Poll timings are not implemented

### ISSUE THREAD

**Issue by cmatthew** [cmatthew/Lind-misc#20]
Poll passes an optional time argument. This is the time to wait before returning unsuccessfully. 

Our implementation of Poll currently does not obey this time, and just returns.

Ideally, we need a polling poll, which runs poll in a loop with a sleep, for up to the time passed.

**Comment by cmatthew** [comment]
OR reformat the poll arguments, and use the select sleep.

**Comment by NitinJami** [comment]
poll timing has been fixed, if timeout >= 0, it waits for that amount of time before it stops polling. If a negative value is given, poll runs for indefinite amount of time (blocking), until an event is triggered in any of the descriptor.
