### ISSUE TITLE
chmod systemcall

### ISSUE THREAD

**Issue by cmatthew** [cmatthew/Lind-misc#28]
We need the chmod system call.

**Comment by JustinCappos** [comment]
This should be very, very easy.   Nitin: do you want to give it a shot?

Thanks,
Justin

On Wed, Jul 4, 2012 at 6:45 PM, Chris Matthews
reply@reply.github.com
wrote:

**Comment by NitinJami** [comment]
Sure prof., I will work on this. Thanks.

**Comment by NitinJami** [comment]
I think we have a new syscall, will close the issue after finalizing in the meeting tomorrow

**Comment by cmatthew** [comment]
Great. I should be able to test this with the lind-fuse system with just a few lines of code.
