### ISSUE TITLE
Bug in select(), improper closing of client socket

### ISSUE THREAD

**Issue by NitinJami** [cmatthew/Lind-misc#31]
While trying to get things right for poll, I found a bug in select() which doesn't close the client sockets properly. When a remote peer closes the connection, the select() needs to trigger an event, which we catch at server side and close the client socket. But this isn't happening.
I am not sure what the problem is, but my initial thoughts are close() needs to be dealt the same way we dealt with accept(), I will look into.

**Comment by NitinJami** [comment]
K, I narrowed the problem, the way we tell the socket is ready is by peeking one byte of data, if there's data, then True is returned else False. The following block is from lind_net_calls.py,  def _nonblock_peek_read(fd):

``` python
  if len(data) == 1:
    return True
  else:
    return False
    # assert False, "Should never here here! data:%s"%(data)
```

but, the way to tell remote socket is closed is by doing a read, if 0 is returned, then we can say that remote socket is closed, so I changed the above code to :

``` python
if len(data) >= 0:
  return True
```

else block is not required as it wouldn't reach there in any case, I think the fix would be to change to the above code.
Can you think of any of other way to know if the remote socket is closed, if the above fix is inappropriate.

**Comment by NitinJami** [comment]
The final fix to the code is as follows :

``` python
  if len(data) == 1: #return True, if data is present...
    return True
  elif len(data) == 0: #return True, since it tells that remote socket is closed...
    return True
  else:
    return False
    # assert False, "Should never here here! data:%s"%(data)
```

It doesn't break any of the tests that I could think of, so I think I will close this Issue.

**Comment by cmatthew** [comment]
Agreed. Thanks!
