### ISSUE TITLE
Special Files

### ISSUE THREAD

**Issue by cmatthew** [cmatthew/Lind-misc#44]
TOR requires support for some special files:
- /dev/null, 
- /sys/devices/system/cpu/*
- /dev/(srandom|urandom|random)

I can copy my local /sys/devices in, and make a blank /dev/null, but we do need the random files for TOR to work.

**Comment by JustinCappos** [comment]
I think we should bite the bullet and make a mock device system.   What I
mean is have the same data in our inode setup and just plug those into
different functions.   I think this won't be too hard to do, right Nitin?
:)

Thanks,
Justin

**Comment by cmatthew** [comment]
Yeah, I don't think it should be too hard.

On Mon, Aug 27, 2012 at 3:36 PM, JustinCappos notifications@github.comwrote:

> I think we should bite the bullet and make a mock device system. What I
> mean is have the same data in our inode setup and just plug those into
> different functions. I think this won't be too hard to do, right Nitin?
> :)
> 
> Thanks,
> Justin
> 
> On Mon, Aug 27, 2012 at 6:18 PM, Chris Matthews notifications@github.comwrote:
> 
> > TOR require support for some special files:
> > - /dev/null,
> > - /sys/devices/system/cpu/*
> > - /dev/(srandom|urandom|random)
> > 
> > I can copy my local /sys/devices in, and make a blank /dev/null, but we
> > do
> > need the random files for TOR to work.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/cmatthew/Lind-misc/issues/44>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cmatthew/Lind-misc/issues/44#issuecomment-8073450.

## 

Chris Matthews
http://www.christophermatthews.ca

**Comment by NitinJami** [comment]
Can u please explain more in depth what I need to do. Thanks

**Comment by JustinCappos** [comment]
Essentially, it would be good to have support for the mknod system call and
the resulting devices ( /dev/null, /dev/random, etc.).

I think the easiest way to do this is to implement mknod and then put
checks in the appropriate system calls to see if it is a device.   If so,
call out to a set of (mostly unimplemented) routines.   The only devices we
need now are /dev/null (1,3), /dev/random (1,8), and /dev/urandom (1,9).
(At least these are the device numbers on the Linux boxes I have checked.)

For random and urandom, just use the randombytes call to get the random
data in response to a read operation.

If you need conceptual help, feel free to ask one of us.

Thanks,
Justin

**Comment by cmatthew** [comment]
I wonder if we actually need to support mknod?  None of the programs are ever going to call mknod directly.  Device drivers numbers are becoming very kernel level.  That said - it is the real interface for setting these up.  I don't want to go too far down a rabbit hole with figuring out a good interface. 

What I was thinking is something where we can replace the operations of particular files with a new function or object.  These would be setup ahead of time so that the program does not have to do it, or during the default lind fs init.  Right now if a few of them are just hard coded in, that is fine. 

The easiest way I can think to implement this is to store something in the inode table which flags the file as a special file.  When the file is opened, replace the usual repy file object in the descriptor table with a different object, which we provide.  This new object will have custom read, write, stat, close, etc functions which act as needed.

**Comment by JustinCappos** [comment]
Meh, I think mknod is simple and similar to other calls we have.   It
should only be a few lines of code.   Let's just implement this.

Thanks,
Justin

**Comment by cmatthew** [comment]
As long as it is doable fast, I don't have an opinion.  This is on the hot path for TOR though, so it has to be ready soon.

**Comment by NitinJami** [comment]
I think i have finished implementing mknod (with some assumptions), i am left with writing custom functions for null, random, urandom. I will let u know as soon as I finish.

urandom is a non-blocking way of random, any ideas how to make this in lind. I think this is not important now, so I will make urandom call random.

Assumptions:
1. It is only used for creating character files.
2. I am not concerned with permissions(S_IRWXA) in mode. Default would be 0666.
3. Major and minor device no.'s should be passed in as a 2-tuple.

Changes to FileSystemMetaData are:
1. dev_id = 5 (for devices) & dev_id = 20 (for rest of files)
2. rdev = set accord. to the device & rdev = none (for regular files).
3. mode = S_IFCHR or S_IFREG 

I will use any of the above flags to call the appropriate reads, writes.

**Comment by cmatthew** [comment]
Those assumptions all sound good to me.

On Wed, Aug 29, 2012 at 12:44 AM, Nitin Jami notifications@github.comwrote:

> I think i have finished implementing mknod (with some assumptions), i am
> left with writing custom functions for null, random, urandom. I will let u
> know as soon as I finish.
> 
> urandom is a non-blocking way of random, any ideas how to make this in
> lind. I think this is not important now, so I will make urandom call random.
> 
> Assumptions:
> 1. It is only used for creating character files.
> 2. I am not concerned with permissions(S_IRWXA) in mode. Default would be
> 0666.
> 3. Major and minor device no.'s should be passed in as a 2-tuple.
> 
> Changes to FileSystemMetaData are:
> 1. dev_id = 5 (for devices) & dev_id = 20 (for rest of files)
> 2. rdev = set accord. to the device & rdev = none (for regular files).
> 3. mode = S_IFCHR or S_IFREG
> 
> I will use any of the above flags to call the appropriate reads, writes.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cmatthew/Lind-misc/issues/44#issuecomment-8117636.

## 

Chris Matthews
http://www.christophermatthews.ca

**Comment by cmatthew** [comment]
Working in TOR.
