### ISSUE TITLE
socketpair

### ISSUE THREAD

**Issue by cmatthew** [cmatthew/Lind-misc#45]
Libevent uses socket pair to create a communication stream to communicate between libevent's signal handlers and the main loop.

http://linux.die.net/man/2/socketpair

Right now we do not have socketpair, but it should not be too hard to implement on top of what we have right now, especially with the special files support.

**Comment by NitinJami** [comment]
I am on it.

**Comment by NitinJami** [comment]
What if we only implemented UDP, what I have done is :

I have binded the two sockets to local interface and ports 50365 and 50366 resp.
I have connected these two sockets. (Connection oriented UDP.)
Now, we can send and recv msg's using recv() and send(). This also makes the programmer not to think about which ports are used, he could just send and recv. Although, we could still use sendto() and recvfrom().

One would argue about the non-reliability of UDP, but socketpair's are used within the local system (From what I understand), so this wouldn't be a much of concern.

I am not preferring TCP, bcoz we need to use a thread for accept-connect to take place, and I am not a fan of having this in our library. It also makes code look much complicated.

Anyways, I have both versions working. I just need your insight.

**Comment by NitinJami** [comment]
After To talking to Prof. Justin, Its been finalized that we will have both versions socktypes.

Also, he has suggested to write socketpair() utilizing some buffer, where writes would be appended to the buffer and consequently reads would be removed from buffer. 

These would less OS dependent and might be fast. But, there may be complications while dealing with UDP. 

I will work on this, and see if its feasible or not. If not we will stick to the original socketpair.

**Comment by JustinCappos** [comment]
For UDP, you could just add messages to a list.   But really, what you've
done is great and will let Chris progress!

Thanks,
Justin

**Comment by cmatthew** [comment]
Works in TOR
