### ISSUE TITLE
accept() should also have flags as an extra argument

### ISSUE THREAD

**Issue by NitinJami** [cmatthew/Lind-misc#53]
If we mark our listening socket as SOCK_NONBLOCK, the connected socket doesn't become non-blocking, since its initializing a new socket descriptor.

In order to support this for connected socket, we need to pass flags in the accept_syscall(), this is according to man pages as well.

**Comment by NitinJami** [comment]
The new accept looks like this: accept_syscall(fd, flags = 0)

**Comment by cmatthew** [comment]
If the flags are already present in net_accept.repy, they should be passed
through.

On Tue, Sep 25, 2012 at 12:35 PM, Nitin Jami notifications@github.comwrote:

> The new accept looks like this: accept_syscall(fd, flags = 0)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cmatthew/Lind-misc/issues/53#issuecomment-8867206.

## 

Chris Matthews
http://www.christophermatthews.ca
