### ISSUE TITLE
CPython fails with an assertion in the filesystem 

### ISSUE THREAD

**Issue by cmatthew** [cmatthew/Lind-misc#54]
Right now Python fails to load because of an assertion in the file system.  This has been verified by Michael as well as Stephen.  The problem is in the stat system call.   Python2.7.2 with a nacl-build script in the the foreign directory.

**Comment by NitinJami** [comment]
When an empty string is passed as path, the lind should raise an ENOENT error, instead of assertion. This also affects any other syscall that has "path" as its argument. eg. open, mkdir, etc. 

This is according to the man pages as well.

**Comment by NitinJami** [comment]
fixed #5969 (svn revision)
