### ISSUE TITLE
In use Lind filesystem should warn when being opened

### ISSUE THREAD

**Issue by cmatthew** [cmatthew/Lind-misc#59]
We should warn the user when they open a Lind filesystem that is already in use elsewhere.  The is a common error when the filesystem is mounted in fuse, since that is easy to forget about.

**Comment by JustinCappos** [comment]
How would we know this is happening?

Is there a test for this?

Thanks,
Justin

**Comment by cmatthew** [comment]
Write a lock file in the same dir as the metadata file.  If the lock file
exists, someone is using it.

On Wed, Oct 17, 2012 at 1:22 PM, JustinCappos notifications@github.comwrote:

> How would we know this is happening?
> 
> Is there a test for this?
> 
> Thanks,
> Justin
> 
> On Wed, Oct 17, 2012 at 4:17 PM, Chris Matthews notifications@github.comwrote:
> 
> > We should warn the user when they open a Lind filesystem that is already
> > in use elsewhere. The is a common error when the filesystem is mounted
> > in
> > fuse, since that is easy to forget about.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/cmatthew/Lind-misc/issues/59>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cmatthew/Lind-misc/issues/59#issuecomment-9542320.

## 

Chris Matthews
http://www.christophermatthews.ca

**Comment by JustinCappos** [comment]
or the system crashed without it being closed...

Let me think if I can devise a more elegant solution.

Thanks,
Justin

**Comment by cmatthew** [comment]
We can't see PIDs in Repy, else we could write a pid in a lock file, then
check if it is still running.

On Wed, Oct 17, 2012 at 1:24 PM, JustinCappos notifications@github.comwrote:

> or the system crashed without it being closed...
> 
> Let me think if I can devise a more elegant solution.
> 
> Thanks,
> Justin
> 
> On Wed, Oct 17, 2012 at 4:23 PM, Chris Matthews notifications@github.comwrote:
> 
> > Write a lock file in the same dir as the metadata file. If the lock file
> > exists, someone is using it.
> > 
> > On Wed, Oct 17, 2012 at 1:22 PM, JustinCappos notifications@github.comwrote:
> > 
> > > How would we know this is happening?
> > > 
> > > Is there a test for this?
> > > 
> > > Thanks,
> > > Justin
> > > 
> > > On Wed, Oct 17, 2012 at 4:17 PM, Chris Matthews <
> > > notifications@github.com>wrote:
> > > 
> > > > We should warn the user when they open a Lind filesystem that is
> > > > already
> > > > in use elsewhere. The is a common error when the filesystem is
> > > > mounted
> > > > in
> > > > fuse, since that is easy to forget about.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/cmatthew/Lind-misc/issues/59>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/cmatthew/Lind-misc/issues/59#issuecomment-9542320>.
> > 
> > ## 
> > 
> > Chris Matthews
> > http://www.christophermatthews.ca
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/cmatthew/Lind-misc/issues/59#issuecomment-9542349>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cmatthew/Lind-misc/issues/59#issuecomment-9542402.

## 

Chris Matthews
http://www.christophermatthews.ca

**Comment by JustinCappos** [comment]
Why do we need to only do this in Repy?   We're using lind-fuse, so it
seems we could reuse the module (runonce) we have for the node manager,
etc. to prevent multiple instances.

Thanks,
Justin

**Comment by NitinJami** [comment]
Fixed in r6270,
