### ISSUE TITLE
chmod needs to obey file 'type' (i.e. dir, device, etc.)

### ISSUE THREAD

**Issue by JustinCappos** [cmatthew/Lind-misc#63]
chmod assumes that whatever it is called on is a file.   If it's a dir (for example), then it changes the fs metadata to say it's a file afterward, regardless.   This is obviously flawed.

**Comment by cmatthew** [comment]
I think this should be high priority.  This  could break app's file systems which trigger it.

**Comment by JustinCappos** [comment]
Fixed in Seattle commit r6427.   (let's sync this over.)
