### ISSUE TITLE
Add file system utility for basic non-FUSE commands...

### ISSUE THREAD

**Issue by JustinCappos** [cmatthew/Lind-misc#65]
It's nice to be able to do basic things without FUSE.   We should have a module that does the basic operations one might need to understand what is in a file system.   Note, something simple that is minimal effort is better than a complete system that takes a long time to build

**Comment by cmatthew** [comment]
We have a simple shell which Paul implemented.  It might not be up to date. It was able to list files, copy files in and out.  It is in the misc repo.

**Comment by JustinCappos** [comment]
Added in Seattle's SVN: via r6248.   

We asked about existing tools 5 days ago and got no response.   I don't know how much duplication exists between the two scripts.
