### ISSUE TITLE
Zombies

### ISSUE THREAD

**Issue by cmatthew** [cmatthew/Lind-misc#67]
Repy leaves Zombie process when running Lind programs. These need to be cleaned up.

**Comment by JustinCappos** [comment]
This doesn't happen with repy, so should be related to the Lind changes.
In particular, check to see if the fork has the parent / child reversed.

**Comment by cmatthew** [comment]
Fixed.

**Comment by JustinCappos** [comment]
How?   Where is the corresponding commit?

**Comment by cmatthew** [comment]
Just sent it in now.  It was just backing out the changes I made to the use of os.fork for fast-lind and cProfile.  Committed as revision r6268.
