### ISSUE TITLE
tester and client should be well seperated

### ISSUE THREAD

**Issue by cmatthew** [cmatthew/Lind-misc#7]
The client.c file should only contain the shared library client code.   A second file test_program.c should make in depth tests of the client stubs.

**Comment by AndiB** [comment]
Please ellaborate on this. I don't know what you are trying to say.
Also note that client.c is not moving forward for now and will probably be deleted as it serves no purpose. As I am working on the uds_client.c as the main thing
client.c and uds_client.c are separate enties.

**Comment by cmatthew** [comment]
Fixed.
